{% set name = "mda-xdrlib" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mda_xdrlib-{{ version }}.tar.gz
  sha256: f26f7158a83c32b96d15b530fce2cbc1190c4b7024e41faa4ab3e3db74e272af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - tomli
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - mda_xdrlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Stand-alone XDRLIB module
  home: https://github.com/MDAnalysis/mda-xdrlib
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orbeckst
    - IAlibay
